name: Sausage Store Deploy

on:
  push:
    branches: [ main ]

env:
  DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USER }}
  DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
  NEXUS_HELM_REPO_USER: ${{ secrets.NEXUS_HELM_REPO_USER }}
  NEXUS_HELM_REPO_PASSWORD: ${{ secrets.NEXUS_HELM_REPO_PASSWORD }}
  NEXUS_HELM_REPO_URL: https://nexus.cloud-services-engineer.education-services.ru/repository/k3kor1u5-sausage-store-helm
  KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
  NAMESPACE: ${{ secrets.NAMESPACE }}
  VAULT_TOKEN: ${{ secrets.VAULT_TOKEN }}
  VAULT_HOST: ${{ secrets.VAULT_HOST }}
  CHART_VERSION: "0.1.2" 

jobs:
  add_helm_chart_to_nexus:
      name: Add Helm Chart To Nexus
      runs-on: ubuntu-latest

      steps:
        - uses: actions/checkout@v3
        - name: Install Helm
          uses: azure/setup-helm@v4
          with:
            version: v3.13.0
        - name: Install Helm Push Plugin
          run: helm plugin install https://github.com/chartmuseum/helm-push

        - name: Package Helm chart
          run: helm package ./sausage-store-chart --version ${{ env.CHART_VERSION }}
          
        - name: Add Nexus Helm repo
          run: |
            helm repo add nexus ${{ env.NEXUS_HELM_REPO_URL }} \
              --username ${{ env.NEXUS_HELM_REPO_USER }} \
              --password ${{ env.NEXUS_HELM_REPO_PASSWORD }}
            helm repo update
        - name: Push chart to Nexus
          run: |
            curl -v -u ${{ env.NEXUS_HELM_REPO_USER }}:${{ env.NEXUS_HELM_REPO_PASSWORD }} \
            --upload-file sausage-store-${{ env.CHART_VERSION }}.tgz \
            ${{ env.NEXUS_HELM_REPO_URL }}/
           